### ISSUE TITLE
Failed on compile, throwing errors

### ISSUE THREAD

**Issue by aliiqbalIntelligenes** [tanepiper/node-bitly#70]
![new error 3](https://user-images.githubusercontent.com/51798492/59588670-94442700-9101-11e9-80ef-b4222f3a9326.PNG)
![new error 2](https://user-images.githubusercontent.com/51798492/59588498-28fa5500-9101-11e9-94f6-42d3cf3df147.PNG)
I'm using Angular and Typescript.
![new error 1](https://user-images.githubusercontent.com/51798492/59588392-ea649a80-9100-11e9-8c21-022d1122ad56.PNG)

**Comment by tanepiper** [comment]
Hi @aliiqbalIntelligenes - it was never really designed to work in the frontend, I suspect that the issue is the library requires`require-promise` and that is a node net library.

I really would not have time to fix this.  My only suggestion would be to instead of using this, create a service in Angular that does the same HTTP request.  My library only supports version 3 of the API too, and Version 4 is the current.

**Comment by aliiqbalIntelligenes** [comment]
Can you please help, how can i pass  group_guid when calling bilty api and what is it? Can you please share what will be the request like when Convert a long url to a Bitlink with group_guid?

**Comment by tanepiper** [comment]
Hi @aliiqbalIntelligenes 

That's an API v4 feature so not supported in this library.  Unfortunately, I have no time to maintain this library so cannot support it.  You would be best to make your own Angular service and call the API directly.
